//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EmployeesWebAPI.DataAccess {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Sql {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Sql() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("EmployeesWebAPI.DataAccess.Sql", typeof(Sql).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на INSERT INTO &quot;Departments&quot; (&quot;Name&quot;, &quot;Phone&quot;)
        ///VALUES (@Name, @Phone)
        ///RETURNING &quot;Id&quot;.
        /// </summary>
        internal static string CreateDepartment {
            get {
                return ResourceManager.GetString("CreateDepartment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на INSERT INTO &quot;Employees&quot; (&quot;Name&quot;, &quot;Surname&quot;, &quot;Phone&quot;, &quot;CompanyId&quot;, &quot;PassportId&quot;, &quot;DepartmentId&quot;)
        ///VALUES (@Name, @Surname, @Phone, @CompanyId, @PassportId, @DepartmentId)
        ///RETURNING &quot;Id&quot;.
        /// </summary>
        internal static string CreateEmployee {
            get {
                return ResourceManager.GetString("CreateEmployee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на INSERT INTO &quot;Passports&quot; (&quot;Type&quot;, &quot;Number&quot;)
        ///VALUES (@Type, @Number)
        ///RETURNING &quot;Id&quot;.
        /// </summary>
        internal static string CreatePassport {
            get {
                return ResourceManager.GetString("CreatePassport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на DELETE FROM &quot;Departments&quot;
        ///WHERE &quot;Id&quot; = @Id.
        /// </summary>
        internal static string DeleteDepartment {
            get {
                return ResourceManager.GetString("DeleteDepartment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на DELETE FROM &quot;Employees&quot;
        ///WHERE &quot;Id&quot; = @Id.
        /// </summary>
        internal static string DeleteEmployee {
            get {
                return ResourceManager.GetString("DeleteEmployee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на DELETE FROM &quot;Passports&quot;
        ///WHERE &quot;Id&quot; = @Id.
        /// </summary>
        internal static string DeletePassport {
            get {
                return ResourceManager.GetString("DeletePassport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на SELECT * FROM &quot;Departments&quot;.
        /// </summary>
        internal static string GetAllDepartments {
            get {
                return ResourceManager.GetString("GetAllDepartments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на SELECT * FROM &quot;Employees&quot;.
        /// </summary>
        internal static string GetAllEmployees {
            get {
                return ResourceManager.GetString("GetAllEmployees", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на SELECT * FROM &quot;Passports&quot;.
        /// </summary>
        internal static string GetAllPassports {
            get {
                return ResourceManager.GetString("GetAllPassports", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на SELECT * FROM &quot;Departments&quot;
        ///WHERE &quot;Id&quot; = @Id.
        /// </summary>
        internal static string GetDepartmentById {
            get {
                return ResourceManager.GetString("GetDepartmentById", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на SELECT * FROM &quot;Employees&quot;
        ///WHERE &quot;Id&quot; = @Id.
        /// </summary>
        internal static string GetEmployeeById {
            get {
                return ResourceManager.GetString("GetEmployeeById", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на SELECT * FROM &quot;Employees&quot;
        ///WHERE &quot;CompanyId&quot; = @CompanyId.
        /// </summary>
        internal static string GetEmployeesByCompanyId {
            get {
                return ResourceManager.GetString("GetEmployeesByCompanyId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на SELECT * FROM &quot;Employees&quot;
        ///WHERE &quot;CompanyId&quot; = @CompanyId AND &quot;DepartmentId&quot; = @DepartmentId.
        /// </summary>
        internal static string GetEmployeesByCompanyIdAndDepartmentId {
            get {
                return ResourceManager.GetString("GetEmployeesByCompanyIdAndDepartmentId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на SELECT * FROM &quot;Passports&quot;
        ///WHERE &quot;Id&quot; = @Id.
        /// </summary>
        internal static string GetPassportById {
            get {
                return ResourceManager.GetString("GetPassportById", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на UPDATE &quot;Departments&quot;
        ///SET 
        ///    &quot;Name&quot; = COALESCE(@Name, &quot;Name&quot;),
        ///    &quot;Phone&quot; = COALESCE(@Phone, &quot;Phone&quot;)
        ///WHERE &quot;Id&quot; = @Id.
        /// </summary>
        internal static string UpdateDepartment {
            get {
                return ResourceManager.GetString("UpdateDepartment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на UPDATE &quot;Employees&quot;
        ///SET 
        ///	&quot;Name&quot; = COALESCE(@Name, &quot;Name&quot;),
        ///	&quot;Surname&quot; = COALESCE(@Surname, &quot;Surname&quot;),
        ///	&quot;Phone&quot; = COALESCE(@Phone, &quot;Phone&quot;),
        ///	&quot;CompanyId&quot; = COALESCE(@CompanyId, &quot;CompanyId&quot;),
        ///	&quot;PassportId&quot; = COALESCE(@PassportId, &quot;PassportId&quot;),
        ///	&quot;DepartmentId&quot; = COALESCE(@DepartmentId, &quot;DepartmentId&quot;)
        ///WHERE &quot;Id&quot; = @Id.
        /// </summary>
        internal static string UpdateEmployee {
            get {
                return ResourceManager.GetString("UpdateEmployee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на UPDATE &quot;Passports&quot;
        ///SET
        ///	&quot;Type&quot; = COALESCE(@Type, &quot;Type&quot;),
        ///	&quot;Number&quot; = COALESCE(@Number, &quot;Number&quot;)
        ///WHERE &quot;Id&quot; = @Id.
        /// </summary>
        internal static string UpdatePassport {
            get {
                return ResourceManager.GetString("UpdatePassport", resourceCulture);
            }
        }
    }
}
